[server]
reload = false
uvicorn_log_level = "debug"

[logging]
level = "DEBUG"
format = "console"

[embedding.cpu]
base_url = "https://www.dmxapi.com/v1/"

[embedding.gpu]
model_path = "BAAI/bge-m3"
devices = "mps"

[llm.discovery]
base_url = "https://www.dmxapi.com/v1/"

[polling]
server_url = ""

[alive_sync]
enabled = false
auto_start = true
provider_base_url = "http://localhost:9009/acps-amp-v1/heartbeat"
kafka_bootstrap_servers = "localhost:19092"
