from __future__ import annotations

from typing import Any, Protocol


class MESAdapter(Protocol):
    async def get_work_orders(self, scope: dict[str, Any]) -> list[dict[str, Any]]: ...
    async def get_work_orders_strict(self, scope: dict[str, Any]) -> list[dict[str, Any]]: ...
    async def import_erp_work_orders(self, orders: list[dict[str, Any]], strategy: str = "update_or_create") -> dict[str, Any]: ...
    async def get_operation_progress(self, work_order_id: str) -> list[dict[str, Any]]: ...
    async def get_wip(self, scope: dict[str, Any]) -> list[dict[str, Any]]: ...
    async def get_quality_records(self, batch_scope: dict[str, Any]) -> list[dict[str, Any]]: ...
    async def get_work_order_documents(self, work_order_id: str) -> list[dict[str, Any]]: ...
    async def upload_engineering_document(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_inspections(self, scope: dict[str, Any]) -> list[dict[str, Any]]: ...
    async def get_work_order_batches(self, work_order_id: str) -> list[dict[str, Any]]: ...
    async def resolve_quality_issue(self, issue_id: str, resolution_notes: str) -> dict[str, Any]: ...
    async def close_quality_issue(self, issue_id: str) -> dict[str, Any]: ...
    async def get_production_documents(self, scope: dict[str, Any]) -> list[dict[str, Any]]: ...
    async def read_authoritative_events(self, scope: dict[str, Any], cursor: str | None = None) -> list[dict[str, Any]]: ...
    async def create_non_authoritative_request(self, request: dict[str, Any]) -> dict[str, Any]: ...
