from __future__ import annotations

from typing import Any, Protocol


class ERPAdapter(Protocol):
    async def get_customer(self, customer_id: str) -> dict[str, Any]: ...
    async def get_item(self, item_id: str, version: str | None = None) -> dict[str, Any]: ...
    async def get_prices(self, item_id: str, as_of: str, supplier: str | None = None) -> list[dict[str, Any]]: ...
    async def get_bom(self, item_id: str, version: str | None = None) -> dict[str, Any]: ...
    async def get_inventory(self, item_ids: list[str]) -> list[dict[str, Any]]: ...
    async def search_suppliers(self, keyword: str, limit: int) -> list[dict[str, Any]]: ...
    async def get_supplier(self, supplier_id: str) -> dict[str, Any]: ...
    async def get_material_demands(self, order_id: str) -> list[dict[str, Any]]: ...
    async def list_sales_orders(self, limit: int = 50) -> list[dict[str, Any]]: ...
    async def get_sales_order(self, order_id: str) -> dict[str, Any]: ...
    async def list_warehouses(self, company: str = "") -> list[dict[str, Any]]: ...
    async def get_default_company(self) -> dict[str, Any]: ...
    async def create_quote_draft(self, draft: dict[str, Any]) -> dict[str, Any]: ...
    async def create_sales_order_draft(self, draft: dict[str, Any]) -> dict[str, Any]: ...
    async def create_purchase_order_draft(self, draft: dict[str, Any]) -> dict[str, Any]: ...
    async def read_back(self, object_ref: dict[str, str]) -> dict[str, Any]: ...
