#!/bin/bash
set -eu
: "${REGISTRY_DB_USER:?}"
: "${REGISTRY_DB_PASSWORD:?}"
: "${REGISTRY_DB_NAME:?}"
: "${CA_DB_USER:?}"
: "${CA_DB_PASSWORD:?}"
: "${CA_DB_NAME:?}"
: "${DISCOVERY_DB_USER:?}"
: "${DISCOVERY_DB_PASSWORD:?}"
: "${DISCOVERY_DB_NAME:?}"
: "${MONITOR_DB_USER:?}"
: "${MONITOR_DB_PASSWORD:?}"
: "${MONITOR_DB_NAME:?}"
: "${KEYCLOAK_DB_USER:?}"
: "${KEYCLOAK_DB_PASSWORD:?}"
: "${KEYCLOAK_DB_NAME:?}"

echo ">>> init app databases (first boot only)"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	DO \$\$ BEGIN
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${REGISTRY_DB_USER}') THEN
	    CREATE USER "${REGISTRY_DB_USER}" WITH PASSWORD '${REGISTRY_DB_PASSWORD}';
	  END IF;
	END \$\$;
	SELECT 'CREATE DATABASE "${REGISTRY_DB_NAME}" OWNER "${REGISTRY_DB_USER}"'
	  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${REGISTRY_DB_NAME}')\gexec

	DO \$\$ BEGIN
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${CA_DB_USER}') THEN
	    CREATE USER "${CA_DB_USER}" WITH PASSWORD '${CA_DB_PASSWORD}';
	  END IF;
	END \$\$;
	SELECT 'CREATE DATABASE "${CA_DB_NAME}" OWNER "${CA_DB_USER}"'
	  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${CA_DB_NAME}')\gexec

	DO \$\$ BEGIN
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DISCOVERY_DB_USER}') THEN
	    CREATE USER "${DISCOVERY_DB_USER}" WITH PASSWORD '${DISCOVERY_DB_PASSWORD}';
	  END IF;
	END \$\$;
	SELECT 'CREATE DATABASE "${DISCOVERY_DB_NAME}" OWNER "${DISCOVERY_DB_USER}"'
	  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DISCOVERY_DB_NAME}')\gexec

	DO \$\$ BEGIN
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MONITOR_DB_USER}') THEN
	    CREATE USER "${MONITOR_DB_USER}" WITH PASSWORD '${MONITOR_DB_PASSWORD}';
	  END IF;
	END \$\$;
	SELECT 'CREATE DATABASE "${MONITOR_DB_NAME}" OWNER "${MONITOR_DB_USER}"'
	  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MONITOR_DB_NAME}')\gexec

	DO \$\$ BEGIN
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${KEYCLOAK_DB_USER}') THEN
	    CREATE USER "${KEYCLOAK_DB_USER}" WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
	  END IF;
	END \$\$;
	SELECT 'CREATE DATABASE "${KEYCLOAK_DB_NAME}" OWNER "${KEYCLOAK_DB_USER}"'
	  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${KEYCLOAK_DB_NAME}')\gexec

	\connect "${DISCOVERY_DB_NAME}"
	CREATE EXTENSION IF NOT EXISTS vector;
EOSQL
echo ">>> init done"
