"""real_agent_runs

Revision ID: 1a1aade41dfd
Revises: d11a1a04ea20
Create Date: 2026-09-28 19:48:44.200046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1aade41dfd'
down_revision: Union[str, Sequence[str], None] = 'd11a1a04ea20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_agent_runs',
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_real_agent_runs_agent_type'), 'real_agent_runs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_real_agent_runs_operation'), 'real_agent_runs', ['operation'], unique=False)
    op.create_index(op.f('ix_real_agent_runs_result_status'), 'real_agent_runs', ['result_status'], unique=False)
    op.create_index(op.f('ix_real_agent_runs_started_at'), 'real_agent_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_real_agent_runs_started_at'), table_name='real_agent_runs')
    op.drop_index(op.f('ix_real_agent_runs_result_status'), table_name='real_agent_runs')
    op.drop_index(op.f('ix_real_agent_runs_operation'), table_name='real_agent_runs')
    op.drop_index(op.f('ix_real_agent_runs_agent_type'), table_name='real_agent_runs')
    op.drop_table('real_agent_runs')
    # ### end Alembic commands ###
