"""initial_schema

Revision ID: 9c45765a095a
Revises: None
Create Date: 2026-09-23 16:40:09.467945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c45765a095a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('consumer', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id', 'consumer')
    )
    op.create_index('ix_inbox_status', 'inbox', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.String(length=120), nullable=False),
    sa.Column('product_id', sa.String(length=120), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=80), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_correlation_id'), 'projects', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_projects_scenario'), 'projects', ['scenario'], unique=False)
    op.create_table('replay_runs',
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('request_idempotency',
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('agent_cases',
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('agent_type', sa.String(length=40), nullable=False),
    sa.Column('operational_state', sa.String(length=40), nullable=False),
    sa.Column('business_state', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_agent_cases_agent_type'), 'agent_cases', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_cases_project_id'), 'agent_cases', ['project_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('audit_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_records_correlation_id'), 'audit_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_records_created_at'), 'audit_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_records_project_id'), 'audit_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_records_trace_id'), 'audit_records', ['trace_id'], unique=False)
    op.create_table('business_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('causation_id', sa.String(length=100), nullable=True),
    sa.Column('source_agent', sa.String(length=40), nullable=True),
    sa.Column('target_agent', sa.String(length=40), nullable=True),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('object_version', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_business_event_idempotency')
    )
    op.create_index(op.f('ix_business_events_correlation_id'), 'business_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_business_events_event_type'), 'business_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_business_events_object_id'), 'business_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_business_events_occurred_at'), 'business_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_business_events_project_id'), 'business_events', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('aip_task_id', sa.String(length=100), nullable=True),
    sa.Column('capability_id', sa.String(length=120), nullable=False),
    sa.Column('protocol_role', sa.String(length=20), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['agent_cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_agent_tasks_case_id'), 'agent_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_trace_id'), 'agent_tasks', ['trace_id'], unique=False)
    op.create_table('approvals',
    sa.Column('approval_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('object_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('approver', sa.String(length=120), nullable=True),
    sa.Column('action_payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['agent_cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approvals_case_id'), 'approvals', ['case_id'], unique=False)
    op.create_index(op.f('ix_approvals_object_id'), 'approvals', ['object_id'], unique=False)
    op.create_index(op.f('ix_approvals_project_id'), 'approvals', ['project_id'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('outbox',
    sa.Column('outbox_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['business_events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('plans',
    sa.Column('plan_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=120), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['agent_cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_plans_case_id'), 'plans', ['case_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('plan_id', sa.String(length=100), nullable=True),
    sa.Column('tool_id', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_tool_calls_project_id'), 'tool_calls', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_project_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_plans_case_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_project_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_object_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_case_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_tasks_trace_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_case_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_business_events_project_id'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_occurred_at'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_object_id'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_event_type'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_correlation_id'), table_name='business_events')
    op.drop_table('business_events')
    op.drop_index(op.f('ix_audit_records_trace_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_project_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_created_at'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_correlation_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_agent_cases_project_id'), table_name='agent_cases')
    op.drop_index(op.f('ix_agent_cases_agent_type'), table_name='agent_cases')
    op.drop_table('agent_cases')
    op.drop_table('request_idempotency')
    op.drop_table('replay_runs')
    op.drop_index(op.f('ix_projects_scenario'), table_name='projects')
    op.drop_index(op.f('ix_projects_correlation_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_inbox_status', table_name='inbox')
    op.drop_table('inbox')
    # ### end Alembic commands ###
