"""real_business_state

Revision ID: d11a1a04ea20
Revises: 9c45765a095a
Create Date: 2026-09-28 19:00:41.949940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11a1a04ea20'
down_revision: Union[str, Sequence[str], None] = '9c45765a095a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_approvals',
    sa.Column('approval_id', sa.String(length=100), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_real_approvals_reference_id'), 'real_approvals', ['reference_id'], unique=False)
    op.create_index(op.f('ix_real_approvals_reference_type'), 'real_approvals', ['reference_type'], unique=False)
    op.create_table('real_procurement_plans',
    sa.Column('plan_id', sa.String(length=100), nullable=False),
    sa.Column('quotation_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('adapter_mode', sa.String(length=20), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_real_procurement_plans_quotation_id'), 'real_procurement_plans', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_real_procurement_plans_status'), 'real_procurement_plans', ['status'], unique=False)
    op.create_table('real_quotations',
    sa.Column('quotation_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('adapter_mode', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=120), nullable=False),
    sa.Column('item_code', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('quotation_id')
    )
    op.create_index(op.f('ix_real_quotations_status'), 'real_quotations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_real_quotations_status'), table_name='real_quotations')
    op.drop_table('real_quotations')
    op.drop_index(op.f('ix_real_procurement_plans_status'), table_name='real_procurement_plans')
    op.drop_index(op.f('ix_real_procurement_plans_quotation_id'), table_name='real_procurement_plans')
    op.drop_table('real_procurement_plans')
    op.drop_index(op.f('ix_real_approvals_reference_type'), table_name='real_approvals')
    op.drop_index(op.f('ix_real_approvals_reference_id'), table_name='real_approvals')
    op.drop_table('real_approvals')
    # ### end Alembic commands ###
